### PR TITLE
Introduce tox, add more tests & fix bugs

### PR DESCRIPTION
**Pull request by boris-42**
- Change structure of the repo where all tests are moved under tests/* directory 
-- All functional tests (one that exists now) are under tests/functional/* 
-- Unit tests are added under tests/unit

- Fix most of code style issues, according to the (PEP8)

- Introduce tox as helper that helps to unify testing experience (this is very very popular tool in python community, downloaded 1M+/month)

- Introduce 4 tox commands:  
  - tox -e py3  to run unittests 
  - tox -e pep8 to run code style checks
  - tox -e cover to run unittests with coverage
  - tox -e func to run existing functional tests 

- Cover with functional tests Node, Edges, Paths 
- Fix found bugs 
- Removed assserts

If this is accepted next steps are planned: 
- To cover rest of functionality with unittests
- Improve a bit code styles by reangling some of style checks
- Refactoring circle CI config to use tox

Note: check commit by commit for simplicity they are separated logical steps

### CODE REVIEW

**Comment by boris-42** [comment]
@gkorland @swilly22 Okay guys before moving with refactoring I think it's good idea to cover everything with unittests, can you please take a look at this PR what do you think?

**Comment by swilly22** [comment]
Hi @boris-42, we really appricate all of your help! I'll review this PR carefully tomorrow morning. thank you!

**Review by swilly22 — APPROVED** [review]

**Comment by swilly22** [comment]
@boris-42 CI currently fails at:
```
run tests
0s
#!/bin/bash -eo pipefail
. venv/bin/activate
coverage run tests/functional/test_all.py
Traceback (most recent call last):
  File "tests/functional/test_all.py", line 2, in <module>
    from tests.utils import base
ModuleNotFoundError: No module named 'tests'

Exited with code exit status 1
CircleCI received exit code 1
```

Care to dig into this?

**Comment by boris-42** [comment]
@swilly22 Will do it today

**Pull request merged**
